### ISSUE TITLE
How to setup log rotation

### ISSUE THREAD

**Issue by gtcat** [napalm-automation/napalm-logs#303]
Hi

I'm using napalm-logs 0.7.0 as a system service on CentOS 7. How should I setup a proper log rotation? Are there options to configure? What is the best practice solution?

Current config:
`cat /usr/lib/systemd/system/napalm-logs.service`
```
[Unit]
Description=napalm-logs
Documentation=https://napalm-logs.readthedocs.io/en/latest/
After=network.target

[Service]
ExecStart=/usr/bin/napalm-logs
Type=simple
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

`cat /etc/napalm/logs `
```
log_level: info
port: 514
disable_security: true
extension_config_path: /etc/napalm/additional_config/
device_whitelist:
  - ios
  - opengear
publisher:
  http:
    address: 'http://elk.<snip>.<snip>:8080'
    method: POST
    headers:
      Content-Type: application/json
    backend: requests
    send_raw: true
    error_whitelist:
      - RXDATA
      - UNKNOWN
      - RAW
  zmq:
    address: 0.0.0.0
    port: 49017
    error_blacklist:
      - RXDATA
```
