### ISSUE TITLE
bad regex for iosxr basic parsing

### ISSUE THREAD

**Issue by Tristou27** [napalm-automation/napalm-logs#364]
For the IOSXR regex, the value of the 'timezone' is matched against 3 characters only. This does not take into account 'CEST' timezone for instance. Then the syslog is not matched at all and not parsed.

A possible modification could be in : [napalm_logs/config/iosxr/init.yml](https://github.com/napalm-automation/napalm-logs/blob/develop/napalm_logs/config/iosxr/init.yml)
```yaml
 timeZone: \s?(\w\w\w)?

... replaced by ...

 timeZone: \s?(\w{0,5}) # 0 to 5 to include: all possible timezones or no timezone
```

Would it be possible to change that?
