### ISSUE TITLE
Problem upgrading napalm-logs to 0.11.0 (python 3)

### ISSUE THREAD

**Issue by teresalves** [napalm-automation/napalm-logs#382]
Hey @mirceaulinic,

We previously had a python2 version deployed from commit 94ff8ad31d5135401b65d396760cac8d765ba805
Since the upgrade, we noticed that a significant amount of messages have been dropped and we so not know why.

Listener: kafka
Publisher: kafka and zmq
Config file:

```
listener:
      kafka:
        bootstrap_servers:
          - stuff
        topic: <reading topic>
    publisher:
      - kafka:
          bootstrap_servers:
            - stuff
          topic: <processed topic>
          send_raw: True
          send_unknown: True
          serializer: json
          no_encrypt: True
      - zmq:
          error_whitelist:
            - BGP_MD5_INCORRECT
            - BGP_PEER_NOT_CONFIGURED
            - BGP_PREFIX_THRESH_EXCEEDED
            - CONFIGURATION_COMMIT_REQUESTED
            - AGENT_INITIALIZED
    buffer:
      mem:
        expire_time: 30
```

The messages that do not show for kafka are also not showing for zmq so it does not look publisher specific.
The amount of messages being consumed by the listener did not go down either.

There are absolutely no errors in the logs.
We saw an example of two seemingly equal messages (apart from the process id) were in the router but only one reached kafka:
```
(...)
Mar 19 03:23:08  router mgd[86521]: UI_COMMIT_COMPLETED:  : commit complete
(...)
Mar 19 03:24:23  router mgd[86605]: UI_COMMIT_COMPLETED:  : commit complete
```

We did some manual commits and we didn't see the message arriving in either zmq or kafka (but when testing again with py2 we saw it passing though in both cases)

We have increased the hwm from 1000 to 10000
We have patched to add an extra backlog option to the pub_proxy and internal zmq publisher 
`+        self.sub.setsockopt(zmq.BACKLOG, 5000)` (line18)

You can evidently see from this graph when the upgrade happened:
![image](https://github.com/napalm-automation/napalm-logs/assets/48688132/5fae42e2-9d91-4ee5-a841-336c661bf81e)

We are not hitting memory or cpu limits but I do notice that if I increase the log level I get less messages being produced. Could threading be influencing this too?

Using bullseye base image with python 3.9
zmq version: 20.0.0 (previously was 19.0.2)
kafka python version: 2.0.1-2 (previously was 1.3.5)

Has anyone seen this before? Or do you have any idea how we can approach this now?
Could there be a particular zmq breaking change between python2 and python3?

Thanks in advance!
